/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paul.pe.cpresentacion;

/**
 *
 * @author Alumno-PB203
 */
public class JPpersonaDocumento extends javax.swing.JPanel {

    /**
     * Creates new form JPpersonaDocumento
     */
    public JPpersonaDocumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPersona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEstadoPersona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bnteliminardatos = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jcTipoDocumento = new javax.swing.JComboBox<>();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("persona");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 60, -1));

        txtPersona.setText("--");
        txtPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 330, 30));

        jLabel3.setText("tipo documento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 100, -1));

        jLabel4.setText("numero documento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 110, -1));

        txtdocumento.setText("--");
        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 330, 30));

        jLabel2.setText("estado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 110, 20));

        txtEstadoPersona.setText("--");
        txtEstadoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstadoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 330, 30));

        jLabel1.setText("registro persona documento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        bnteliminardatos.setText("eliminar");
        bnteliminardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnteliminardatosActionPerformed(evt);
            }
        });
        jPanel1.add(bnteliminardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        btnguardar.setText("guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, -1, -1));

        jcTipoDocumento.setBorder(null);
        jPanel1.add(jcTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonaActionPerformed

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoActionPerformed

    private void bnteliminardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnteliminardatosActionPerformed

    }//GEN-LAST:event_bnteliminardatosActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtEstadoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoPersonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnteliminardatos;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcTipoDocumento;
    private javax.swing.JTextField txtEstadoPersona;
    private javax.swing.JTextField txtPersona;
    private javax.swing.JTextField txtdocumento;
    // End of variables declaration//GEN-END:variables
}
