/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paul.pe.cpresentacion;

import com.paul.pe.cmodelo.TipoDocumento;
import com.paul.pe.cnegocio.TipoDocumentoBO;
import com.paul.pe.db.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno-PB203
 */
public class JPTipoDocumento extends javax.swing.JPanel {
    TipoDocumentoBO tdbo = new  TipoDocumentoBO();
    TipoDocumento td = new TipoDocumento();
    String idTipoDocumento="0";
            
    public JPTipoDocumento() {
        initComponents();
        listarTipoDocumento();
    }
    
    public void listarTipoDocumento(){
        tdbo.listarTipoDocumento(TablaTipoDocumento);
    }

    /**
     * Creates new form JPTipoDocumento2
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTipoDocumento = new javax.swing.JTable();
        bnteditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtsigla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtorden = new javax.swing.JTextField();
        txtfechaactualizacion = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        bnteliminardatos = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        escritorio2.setBackground(new java.awt.Color(255, 255, 255));
        escritorio2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CRUD tipo documento");
        escritorio2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 98, -1, -1));

        TablaTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        TablaTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaTipoDocumentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaTipoDocumento);

        escritorio2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        bnteditar.setText("modificar");
        bnteditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnteditarMouseClicked(evt);
            }
        });
        bnteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnteditarActionPerformed(evt);
            }
        });
        escritorio2.add(bnteditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, -1, -1));

        btneliminar.setText("eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        escritorio2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, -1, -1));

        jLabel2.setText("fecha actualizacion");
        escritorio2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 110, 20));

        txtsigla.setText("sigla");
        txtsigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsiglaActionPerformed(evt);
            }
        });
        escritorio2.add(txtsigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 330, 30));

        jLabel3.setText("estado");
        escritorio2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, -1));

        jLabel4.setText("sigla");
        escritorio2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 60, -1));

        jLabel5.setText("orden");
        escritorio2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 60, -1));

        txtorden.setText("orden");
        escritorio2.add(txtorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 330, 30));

        txtfechaactualizacion.setText("fecha de actualizacion");
        escritorio2.add(txtfechaactualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 330, 30));

        txtestado.setText("estado");
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        escritorio2.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 330, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        escritorio2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 320, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        escritorio2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 320, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        escritorio2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 320, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        escritorio2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 320, 20));

        bnteliminardatos.setText("eliminar");
        bnteliminardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnteliminardatosActionPerformed(evt);
            }
        });
        escritorio2.add(bnteliminardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));

        btnguardar.setText("guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        escritorio2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, -1, -1));

        jLabel7.setText("nombre");
        escritorio2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 60, -1));

        txtnombre1.setText("nombre");
        txtnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre1ActionPerformed(evt);
            }
        });
        escritorio2.add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 330, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        escritorio2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio2, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(escritorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsiglaActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
       try{
           TipoDocumento tdf = new TipoDocumento();
        tdf.setIdTipoDocumento(Integer.parseInt(idTipoDocumento));
        tdbo.eliminarTipoDocomento(tdf);
        listarTipoDocumento();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error"+ ex.getMessage());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void bnteliminardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnteliminardatosActionPerformed
        txtnombre1.setText((""));
        txtestado.setText("");  // Limpia un JTextField
         txtsigla.setText("");  // Limpia un JTextField
         txtorden.setText("");  // Limpia un JTextField
       //  txtfechaactualizacion.setText("");  // Limpia un JTextField
         //txtfecharegistro.setText("");  // Limpia un JTextField
    
    }//GEN-LAST:event_bnteliminardatosActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
 

  try {
      if(valida()){
      td.setNombre(txtnombre1.getText());
      td.setEstado(txtestado.getText());
      td.setOrden(Integer.parseInt(txtorden.getText()));
      td.setSigla(txtsigla.getText());
      td.setFechaActualiza(txtfechaactualizacion.getText());      
      tdbo.agregarTipoDocomento(td); 
      listarTipoDocumento();
      JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
      System.out.println(e.getMessage());
      
    }    
        

  
        
    }//GEN-LAST:event_btnguardarActionPerformed
    
    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre1ActionPerformed

    private void TablaTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaTipoDocumentoMouseClicked
        int seleccion = TablaTipoDocumento.rowAtPoint(evt.getPoint());
        idTipoDocumento = TablaTipoDocumento.getValueAt(seleccion, 0)+"";
        txtnombre1.setText(TablaTipoDocumento.getValueAt(seleccion, 1)+"");
        txtestado.setText(TablaTipoDocumento.getValueAt(seleccion, 2)+"");
        txtorden.setText(TablaTipoDocumento.getValueAt(seleccion, 3)+"");
        txtsigla.setText(TablaTipoDocumento.getValueAt(seleccion, 4)+"");
        
        
        System.out.println(seleccion);
    }//GEN-LAST:event_TablaTipoDocumentoMouseClicked

    private void bnteditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnteditarMouseClicked
         try {
             if(valida()){
                 

             td.setIdTipoDocumento(Integer.parseInt(idTipoDocumento));
            td.setNombre(txtnombre1.getText());
          td.setEstado(txtestado.getText());
           td.setOrden(Integer.parseInt(txtestado.getText()));
           td.setSigla(txtsigla.getText());
          // td.setFecha(txtfecharegistro.getText());
          td.setFechaActualiza(txtfechaactualizacion.getText());
           tdbo.modificarTipoDocumento(td); 
           listarTipoDocumento();
           JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
             }
         }catch (SQLException e) {
          JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
 
                } catch (ParseException ex) {
            Logger.getLogger(JPTipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bnteditarMouseClicked

    private void bnteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnteditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnteditarActionPerformed
   public boolean valida(){
       if(txtnombre1.getText().equals("")){
           JOptionPane.showMessageDialog(null, "nombre es requerido");
       }else if(txtsigla.getText().equals("")){
           JOptionPane.showMessageDialog(null, "sigla es requerida ");
           return false;
       }
       return true;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTipoDocumento;
    private javax.swing.JButton bnteditar;
    private javax.swing.JButton bnteliminardatos;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JPanel escritorio2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechaactualizacion;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtorden;
    private javax.swing.JTextField txtsigla;
    // End of variables declaration//GEN-END:variables
}
